# Generated by Django 2.1.5 on 2019-01-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_name',
            field=models.CharField(default='Tango', max_length=50, null=True, verbose_name='作者'),
        ),
    ]
